#[macro_use]
extern crate rustpython_derive;

use nanopython_core::Capability;
use nanopython_plugin_api::Plugin;
use rustpython_vm::{VirtualMachine, py_freeze};

mod native_modules;

pub struct StdlibCorePlugin;

impl Plugin for StdlibCorePlugin {
    fn name(&self) -> &'static str {
        "stdlib-core"
    }

    fn provides(&self) -> &'static [Capability] {
        &[Capability::StdlibCore]
    }

    fn install(&self, vm: &mut VirtualMachine) -> nanopython_core::Result<()> {
        vm.add_native_modules(native_modules::get_module_inits());

        vm.add_frozen(py_freeze!(
            source = r#"
# Generated by nanopython-stdlib-core.
# Block modules that are intentionally out of scope for the min profile.

import sys

_BLOCKED_ROOTS = {
    "asyncio",
    "threading",
    "multiprocessing",
    "pickle",
    "socket",
}


class _NanoPythonBlockedFinder:
    def find_spec(self, fullname, path=None, target=None):
        root = fullname.split(".", 1)[0]
        if root in _BLOCKED_ROOTS:
            raise ImportError(
                f"module '{fullname}' is disabled in nanopython min profile"
            )
        return None


sys.meta_path.insert(0, _NanoPythonBlockedFinder())
"#,
            module_name = "sitecustomize"
        ));
        Ok(())
    }
}

pub fn plugin() -> StdlibCorePlugin {
    StdlibCorePlugin
}
