#[derive(Debug, Clone, Eq, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub line: usize,
    pub col: usize,
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum TokenKind {
    Name(String),
    Int(i64),
    Str(String),
    FStr(String),
    Keyword(Keyword),
    Newline,
    Indent,
    Dedent,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Dot,
    At,
    Plus,
    Minus,
    Star,
    Slash,
    SlashSlash,
    Percent,
    Amp,
    Pipe,
    Caret,
    LShift,
    RShift,
    Eq,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    SlashSlashEq,
    PercentEq,
    AmpEq,
    PipeEq,
    CaretEq,
    LShiftEq,
    RShiftEq,
    EqEq,
    NotEq,
    Lt,
    Lte,
    Gt,
    Gte,
    Eof,
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum Keyword {
    If,
    Elif,
    Else,
    For,
    In,
    While,
    Def,
    Return,
    Raise,
    Break,
    Continue,
    Pass,
    Import,
    From,
    As,
    Class,
    With,
    And,
    Or,
    Not,
    Is,
    True,
    False,
    None,
    Yield,
    Try,
    Except,
    Finally,
    Lambda,
}

pub fn keyword(name: &str) -> Option<Keyword> {
    match name {
        "if" => Some(Keyword::If),
        "elif" => Some(Keyword::Elif),
        "else" => Some(Keyword::Else),
        "for" => Some(Keyword::For),
        "in" => Some(Keyword::In),
        "while" => Some(Keyword::While),
        "def" => Some(Keyword::Def),
        "return" => Some(Keyword::Return),
        "raise" => Some(Keyword::Raise),
        "break" => Some(Keyword::Break),
        "continue" => Some(Keyword::Continue),
        "pass" => Some(Keyword::Pass),
        "import" => Some(Keyword::Import),
        "from" => Some(Keyword::From),
        "as" => Some(Keyword::As),
        "class" => Some(Keyword::Class),
        "with" => Some(Keyword::With),
        "and" => Some(Keyword::And),
        "or" => Some(Keyword::Or),
        "not" => Some(Keyword::Not),
        "is" => Some(Keyword::Is),
        "True" => Some(Keyword::True),
        "False" => Some(Keyword::False),
        "None" => Some(Keyword::None),
        "yield" => Some(Keyword::Yield),
        "try" => Some(Keyword::Try),
        "except" => Some(Keyword::Except),
        "finally" => Some(Keyword::Finally),
        "lambda" => Some(Keyword::Lambda),
        _ => None,
    }
}
